import numpy as np
import matplotlib.pyplot as plt


# HW3
# q3.1 : 

def read_Cp(filename, headerLines=3):
    """ reads a pressure coefficient file generated by xfoil """
    data = np.loadtxt(filename, skiprows=3, usecols=(0, 1, 2))
    x  = data[:, 0]          # x/c
    y  = data[:, 1]          # y/c (useful for checking geometry)
    Cp = data[:, 2]          # pressure coefficient
    return x, y, Cp


def read_polar(filename, headerLines=12):
    """ reads a polar generated by xfoil """
    data = np.loadtxt(filename, skiprows=headerLines, usecols=(0, 1, 2, 4), comments=None, unpack=True )
    alphas, cls, cds, cms = data[0], data[1], data[2], data[3]

    # Sort by angle of attack
    sort_idx = np.argsort(alphas)
    alphas = alphas[sort_idx]
    cls    = cls[sort_idx]
    cds    = cds[sort_idx]
    cms    = cms[sort_idx]
    
    return alphas, cls, cds, cms

# 3.2d
def airfoil_force(x, y, p):
    # Calculations
    dx = x[1:] - x[:-1]
    dy = y[1:] - y[:-1]
    ds = np.sqrt(dx**2 + dy**2)   # panel length

    # normal vector
    tx = dx / ds
    ty = dy / ds

    # (tx, ty) → (ty, -tx)
    nx =  ty
    ny = -tx

    #calculating pressure at midpoints
    p_mid = 0.5 * (p[:-1] + p[1:])

    # formula calc: dF = -p * n_hat * ds
    fx = -np.sum(p_mid * nx * ds)
    fy = -np.sum(p_mid * ny * ds)

    return fx, fy




#Trying to plot

# q1.a 
x, y, Cp = read_Cp("q3.1_Cp.xfoil")
#plotting part a

plt.plot(x, Cp)
plt.xlabel('x')
plt.ylabel('Cp')
ax = plt.gca()
ax.yaxis.set_inverted(True)  # Invert y-axis for Cp
plt.title('Pressure Coefficient Distribution')
plt.show()


# q1.b 
alphas, cls, cds, cms = read_polar("q3.b_polar.xfoil")
# plotting part b
plt.plot(cds, cls, marker='o')
plt.xlabel('Coefficient of Drag (Cd)')
plt.ylabel('Coefficient of Lift (Cl)')
plt.title('Airfoil Polar Diagram')
plt.show()



#q2.d
# fx, fy = airfoil_force("q3.2f_Cp.xfoil")
x2, y2, Cp2 = read_Cp("q3.2f_Cp.xfoil")
Cx, Cy = airfoil_force(x2, y2, Cp2)

#Finding Cx and Cy
print(f"Cx = {Cx:.4f}")
print(f"Cy = {Cy:.4f}")

# Xfoil is counter clockwise so rotation nedded
#Finding Cl and Cd
alpha_deg = 4.0
alpha_rad = np.deg2rad(alpha_deg)
Cl = Cy * np.cos(alpha_rad) + Cx * np.sin(alpha_rad)
Cd = Cy * np.sin(alpha_rad) + Cx * np.cos(alpha_rad)
print(f"Cl = {Cl:.4f}")
print(f"Cd = {Cd:.4f}")

#plotting  for f
plt.plot(Cd, Cl, marker='o', color='red')
plt.plot(cds, cls, marker='o')
plt.xlabel('Coefficient of Drag (Cd)')
plt.ylabel('Coefficient of Lift (Cl)')
plt.title('Total Pressure Force Function')
plt.show()

plt.plot(cds, cls, marker='o')










# #test case: 
# # Pascal's law — Uniform pressure cancels out on any closed surface

# theta = np.linspace(0, 2*np.pi, 1000, endpoint=False)
# x_c = np.append(np.cos(theta), np.cos(theta[0]))
# y_c = np.append(np.sin(theta), np.sin(theta[0]))
# p_uniform = 5.0 * np.ones_like(x_c)
# fx_t1, fy_t1 = airfoil_force(x_c, y_c, p_uniform)
# #print(f"Test 1 - Uniform p:  fx={fx_t1:.6f}, fy={fy_t1:.6f}  (expected 0, 0)")







